### ISSUE TITLE
API: New mixin #a.keyframesV2

### ISSUE THREAD

**Issue by codeworksdev** [codeworksdev/animate.less#30]
Most browsers currently support unprefixed `@keyframes`, so the legacy compile method is no longer necessary for the majority of real-world applications out there. For this reason, we've decided to split the `#a.keyframes` mixin into two versions:

## VERSION 1 (LEGACY)
_Generates all the necessary vendor prefixes for `@keyframes`, but it is no longer recommended to use in your projects unless absolutely necessary._
```less
.keyframesV1(@name; @frames) {
    @-webkit-keyframes @name { @vendor: -webkit-; @frames(); }
       @-moz-keyframes @name { @vendor: -moz-;    @frames(); }
         @-o-keyframes @name { @vendor: -o-;      @frames(); }
            @keyframes @name { @vendor: ~'';      @frames(); }
    }
```

## VERSION 2
_Recommended version._
```less
.keyframesV2(@name; @frames) {
    @keyframes @name { @vendor: ~''; @frames(); }
    }
